name: pdfmixtool
confinement: strict
grade: stable
base: core20
adopt-info: pdfmixtool
    
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  #- build-on: i386 # Not supported by core20
  - build-on: ppc64el
  - build-on: s390x

plugs:
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

apps:
  pdfmixtool:
    command: bin/desktop-launch $SNAP/usr/bin/pdfmixtool
    common-id: eu.scarpetta.PDFMixTool
    desktop: usr/share/applications/eu.scarpetta.PDFMixTool.desktop
    plugs:
      - home
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - opengl
      - removable-media
      - gsettings
    environment:
      HOME: "$SNAP_USER_COMMON"

parts:
  pdfmixtool:
    after:
      - libqpdf
      - desktop-qt5
    source: https://gitlab.com/scarpetta/pdfmixtool/-/archive/v1.0beta/pdfmixtool-v1.0beta.tar.gz
    override-pull: |
      snapcraftctl pull
      # Point icon to the correct location
      sed -i.bak -i -e 's|Icon=eu.scarpetta.PDFMixTool|Icon=/usr/share/icons/hicolor/scalable/apps/eu.scarpetta.PDFMixTool.svg|g' resources/eu.scarpetta.PDFMixTool.desktop
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
    parse-info:
      - usr/share/metainfo/eu.scarpetta.PDFMixTool.appdata.xml
    build-packages:
      - build-essential
      - qtbase5-dev
      - qttools5-dev
    stage-packages:
      - dbus
      - qttranslations5-l10n # common translations
      - qtwayland5
      - qt5-gtk-platformtheme # for theming, font settings, cursor and to use gtk3 file chooser
      - qt5-style-plugins # for mouse cursor theme fix

  libqpdf:
    plugin: make
    override-build: |
      ./configure --prefix=/usr --disable-static
      make
      make DESTDIR=$SNAPCRAFT_PART_INSTALL install
    source: https://github.com/qpdf/qpdf/releases/download/release-qpdf-10.3.1/qpdf-10.3.1.tar.gz
    build-packages:
      - build-essential
      - pkg-config
      - libjpeg8-dev
      - zlib1g-dev
    stage-packages:
      - libjpeg8
      - zlib1g

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - dpkg-dev
      - qtbase5-dev
    stage-packages:
      - adwaita-icon-theme
      - dmz-cursor-theme
      - gnome-themes-standard
      - libgdk-pixbuf2.0-0
      - libgl1-mesa-dri
      - libglu1-mesa
      - libqt5gui5
      - libqt5svg5
      - libxkbcommon0
      - light-themes
      - locales-all
      - shared-mime-info
      - ttf-ubuntu-font-family
      - qt5-gtk-platformtheme
      - qtwayland5
      - xdg-user-dirs
    override-prime: |
      snapcraftctl prime
      sed -i 's|XDG_DATA_HOME=$SNAP_USER_DATA|XDG_DATA_HOME=$SNAP_USER_COMMON|' $SNAPCRAFT_PRIME/bin/desktop-launch
      sed -i 's|XDG_CONFIG_HOME=$SNAP_USER_DATA|XDG_CONFIG_HOME=$SNAP_USER_COMMON|' $SNAPCRAFT_PRIME/bin/desktop-launch
  desktop-settings-packages:
    plugin: nil
    build-packages:
      - libglib2.0-bin
    stage-packages:
      - gsettings-desktop-schemas
      - ubuntu-settings
    prime:
      - usr/share/glib-2.0/schemas/*
    after: [desktop-qt5]
  desktop-settings-build:
    plugin: nil
    after: [desktop-settings-packages]
    override-prime: |
      set -eux
      glib-compile-schemas usr/share/glib-2.0/schemas
