name: pdfmixtool
version: 1.0beta
confinement: strict
grade: stable
base: core20
adopt-info: pdfmixtool
apps:
  pdfmixtool:
    common-id: eu.scarpetta.PDFMixTool.desktop
    command: usr/bin/pdfmixtool
    plugs:
    - desktop
    - desktop-legacy
    - opengl
    - wayland
    - x11
    - home
    - removable-media
    command-chain:
    - snap/command-chain/desktop-launch
parts:
  pdfmixtool:
    after:
    - libqpdf
    plugin: cmake
    source: https://gitlab.com/scarpetta/pdfmixtool/-/archive/v1.0beta/pdfmixtool-v1.0beta.tar.gz
    cmake-parameters:
    - -DCMAKE_INSTALL_PREFIX=/usr
    - -DCMAKE_BUILD_TYPE=Release
    parse-info:
    - usr/share/metainfo/eu.scarpetta.PDFMixTool.appdata.xml
    build-environment: &id001
    - SNAPCRAFT_CMAKE_ARGS: -DCMAKE_FIND_ROOT_PATH=/snap/kde-frameworks-5-qt-5-15-core20-sdk/current
  libqpdf:
    plugin: make
    override-build: |
      ./configure --prefix=/usr --disable-static
      make
      make DESTDIR=$SNAPCRAFT_PART_INSTALL install
    source: https://github.com/qpdf/qpdf/releases/download/release-qpdf-10.3.1/qpdf-10.3.1.tar.gz
    build-packages:
    - build-essential
    - pkg-config
    - libjpeg8-dev
    - zlib1g-dev
    stage-packages:
    - libjpeg8
    - zlib1g
    build-environment: *id001
  kde-neon-extension:
    build-packages:
    - g++
    build-snaps:
    - kde-frameworks-5-qt-5-15-core20-sdk/latest/candidate
    make-parameters:
    - PLATFORM_PLUG=kde-frameworks-5-plug
    plugin: make
    source: $SNAPCRAFT_EXTENSIONS_DIR/desktop
    source-subdir: kde-neon
assumes:
- snapd2.43
plugs:
  icon-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/icons
  kde-frameworks-5-plug:
    content: kde-frameworks-5-qt-5-15-core20-all
    default-provider: kde-frameworks-5-qt-5-15-core20
    interface: content
    target: $SNAP/kf5
  sound-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/sounds
environment:
  SNAP_DESKTOP_RUNTIME: $SNAP/kf5
hooks:
  configure:
    command-chain:
    - snap/command-chain/hooks-configure-desktop
    plugs:
    - desktop
