name: pdfmixtool
base: core18
adopt-info: pdfmixtool
grade: stable
confinement: strict
architectures:
  - build-on: amd64

apps:
  pdfmixtool:
    command: usr/bin/pdfmixtool
    common-id: eu.scarpetta.PDFMixTool
    environment:
      # Set theme fix on gnome/gtk
      QT_QPA_PLATFORMTHEME: gtk3
    desktop: usr/share/applications/eu.scarpetta.PDFMixTool.desktop
    extensions:
      - kde-neon
    plugs:
      - home
      - removable-media
      - unity7
      - opengl

parts:
  pdfmixtool:
    after:
      - libqpdf
    source: https://gitlab.com/scarpetta/pdfmixtool/-/archive/v1.0.1/pdfmixtool-v1.0.1.tar.gz
    override-pull: |
      snapcraftctl pull
      # Point icon to the correct location
      sed -i.bak -i -e 's|Icon=eu.scarpetta.PDFMixTool|Icon=/usr/share/icons/hicolor/scalable/apps/eu.scarpetta.PDFMixTool.svg|g' resources/eu.scarpetta.PDFMixTool.desktop
    plugin: cmake
#    cmake-parameters:
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_FIND_ROOT_PATH=/snap/kde-frameworks-5-core18-sdk/current
    parse-info:
      - usr/share/metainfo/eu.scarpetta.PDFMixTool.appdata.xml
    build-snaps:
      - kde-frameworks-5-core18-sdk
    build-packages:
      - libglvnd-dev
      - libx11-dev

  libqpdf:
    plugin: make
    override-build: |
      ./configure --prefix=/usr --disable-static
      make
      make DESTDIR=$SNAPCRAFT_PART_INSTALL install
    source: https://github.com/qpdf/qpdf/releases/download/release-qpdf-10.3.2/qpdf-10.3.2.tar.gz
    build-packages:
      - build-essential
      - pkg-config
      - libjpeg8-dev
      - zlib1g-dev
    stage-packages:
      - libjpeg8
      - zlib1g
