name: pdfmixtool
confinement: strict
grade: stable
base: core20
adopt-info: pdfmixtool
    
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  #- build-on: i386 # Not supported by core20
  - build-on: ppc64el
  - build-on: s390x

apps:
  pdfmixtool:
    command: bin/desktop-launch $SNAP/usr/bin/pdfmixtool
    desktop: usr/share/applications/eu.scarpetta.PDFMixTool.desktop
    plugs:
      - home
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - opengl
      - removable-media

parts:
  pdfmixtool:
    after:
      - libqpdf
      - desktop-qt5
    plugin: cmake
    plugin: cmake
    source: https://gitlab.com/scarpetta/pdfmixtool/-/archive/v1.0beta/pdfmixtool-v1.0beta.tar.gz
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
    parse-info:
      - usr/share/metainfo/eu.scarpetta.PDFMixTool.appdata.xml
    build-packages:
      - build-essential
      - qtbase5-dev
      - qttools5-dev
    stage-packages:
      - dbus
      - qttranslations5-l10n # common translations
      - qtwayland5
      - qt5-gtk-platformtheme # for theming, font settings, cursor and to use gtk3 file chooser
      - qt5-style-plugins # for mouse cursor theme fix

  libqpdf:
    plugin: make
    override-build: |
      ./configure --prefix=/usr --disable-static
      make
      make DESTDIR=$SNAPCRAFT_PART_INSTALL install
    source: https://github.com/qpdf/qpdf/releases/download/release-qpdf-10.3.1/qpdf-10.3.1.tar.gz
    build-packages:
      - build-essential
      - pkg-config
      - libjpeg8-dev
      - zlib1g-dev
    stage-packages:
      - libjpeg8
      - zlib1g

  # Remote part for support of various desktop technologies
  # Refer: https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
